version: "3"
services:
  app:
    environment:
      - PORT=3000
      - NODE_ENV=production
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    container_name: app
    restart: always
    build: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
    networks:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - postgres
networks:
  postgres:
    driver: bridge